project:
  type: website

website:
  title: "STAC Sprint Tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: rstac.qmd
        text: Downloading data using R
      - href: gdal_cli.qmd
        text: Downloading data using a CLI

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
