project:
  type: website
  output-dir: docs

website:
  title: "STAC Sprint Tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: rstac.qmd
        text: Downloading data using R
      - href: gdal_cli.qmd
        text: Downloading data using a CLI
      - href: r_cql.qmd
        text: Using rstac and CQL2 to query STAC APIs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
